transform-data-strings: transform-date-strings.cc
	g++ transform-date-strings.cc  -o transform-date-strings -std=c++17 -g

clean:
	rm transform-date-strings

test:
	./transform-date-strings < testdata.txt